/** Declaration file generated by dts-gen */

export const SEFLG_ASTROMETRIC: number;

export const SEFLG_BARYCTR: number;

export const SEFLG_DEFAULTEPH: number;

export const SEFLG_DPSIDEPS_1980: number;

export const SEFLG_EQUATORIAL: number;

export const SEFLG_HELCTR: number;

export const SEFLG_ICRS: number;

export const SEFLG_J2000: number;

export const SEFLG_JPLEPH: number;

export const SEFLG_JPLHOR: number;

export const SEFLG_JPLHOR_APPROX: number;

export const SEFLG_MOSEPH: number;

export const SEFLG_NOABERR: number;

export const SEFLG_NOGDEFL: number;

export const SEFLG_NONUT: number;

export const SEFLG_ORBEL_AA: number;

export const SEFLG_RADIANS: number;

export const SEFLG_SIDEREAL: number;

export const SEFLG_SPEED: number;

export const SEFLG_SPEED3: number;

export const SEFLG_SWIEPH: number;

export const SEFLG_TOPOCTR: number;

export const SEFLG_TRUEPOS: number;

export const SEFLG_XYZ: number;

export const SE_ACRONYCHAL_RISING: number;

export const SE_ACRONYCHAL_SETTING: number;

export const SE_ADMETOS: number;

export const SE_APOLLON: number;

export const SE_APP_TO_TRUE: number;

export const SE_ARMC: number;

export const SE_ASC: number;

export const SE_AST_OFFSET: number;

export const SE_AUNIT_TO_KM: number;

export const SE_AUNIT_TO_LIGHTYEAR: number;

export const SE_AUNIT_TO_PARSEC: number;

export const SE_BIT_ASTRO_TWILIGHT: number;

export const SE_BIT_CIVIL_TWILIGHT: number;

export const SE_BIT_DISC_BOTTOM: number;

export const SE_BIT_DISC_CENTER: number;

export const SE_BIT_FIXED_DISC_SIZE: number;

export const SE_BIT_GEOCTR_NO_ECL_LAT: number;

export const SE_BIT_NAUTIC_TWILIGHT: number;

export const SE_BIT_NO_REFRACTION: number;

export const SE_CALC_ITRANSIT: number;

export const SE_CALC_MTRANSIT: number;

export const SE_CALC_RISE: number;

export const SE_CALC_SET: number;

export const SE_CERES: number;

export const SE_CHIRON: number;

export const SE_COASC1: number;

export const SE_COASC2: number;

export const SE_COMET_OFFSET: number;

export const SE_COSMICAL_SETTING: number;

export const SE_CUPIDO: number;

export const SE_EARTH: number;

export const SE_ECL2HOR: number;

export const SE_ECL_1ST_VISIBLE: number;

export const SE_ECL_2ND_VISIBLE: number;

export const SE_ECL_3RD_VISIBLE: number;

export const SE_ECL_4TH_VISIBLE: number;

export const SE_ECL_ALLTYPES_LUNAR: number;

export const SE_ECL_ALLTYPES_SOLAR: number;

export const SE_ECL_ANNULAR: number;

export const SE_ECL_ANNULAR_TOTAL: number;

export const SE_ECL_CENTRAL: number;

export const SE_ECL_MAX_VISIBLE: number;

export const SE_ECL_NONCENTRAL: number;

export const SE_ECL_NUT: number;

export const SE_ECL_OCC_BEG_DAYLIGHT: number;

export const SE_ECL_OCC_END_DAYLIGHT: number;

export const SE_ECL_ONE_TRY: number;

export const SE_ECL_PARTBEG_VISIBLE: number;

export const SE_ECL_PARTEND_VISIBLE: number;

export const SE_ECL_PARTIAL: number;

export const SE_ECL_PENUMBBEG_VISIBLE: number;

export const SE_ECL_PENUMBEND_VISIBLE: number;

export const SE_ECL_PENUMBRAL: number;

export const SE_ECL_TOTAL: number;

export const SE_ECL_TOTBEG_VISIBLE: number;

export const SE_ECL_TOTEND_VISIBLE: number;

export const SE_ECL_VISIBLE: number;

export const SE_EQU2HOR: number;

export const SE_EQUASC: number;

export const SE_EVENING_FIRST: number;

export const SE_EVENING_LAST: number;

export const SE_FICT_MAX: number;

export const SE_FICT_OFFSET: number;

export const SE_FICT_OFFSET_1: number;

export const SE_FIXSTAR: number;

export const SE_GREG_CAL: number;

export const SE_HADES: number;

export const SE_HARRINGTON: number;

export const SE_HELFLAG_AVKIND: number;

export const SE_HELFLAG_AVKIND_MIN7: number;

export const SE_HELFLAG_AVKIND_MIN9: number;

export const SE_HELFLAG_AVKIND_PTO: number;

export const SE_HELFLAG_AVKIND_VR: number;

export const SE_HELFLAG_HIGH_PRECISION: number;

export const SE_HELFLAG_LONG_SEARCH: number;

export const SE_HELFLAG_NO_DETAILS: number;

export const SE_HELFLAG_OPTICAL_PARAMS: number;

export const SE_HELFLAG_SEARCH_1_PERIOD: number;

export const SE_HELFLAG_VISLIM_DARK: number;

export const SE_HELFLAG_VISLIM_NOMOON: number;

export const SE_HELFLAG_VISLIM_PHOTOPIC: number;

export const SE_HELIACAL_RISING: number;

export const SE_HELIACAL_SETTING: number;

export const SE_HOR2ECL: number;

export const SE_HOR2EQU: number;

export const SE_INTP_APOG: number;

export const SE_INTP_PERG: number;

export const SE_ISIS: number;

export const SE_JUL_CAL: number;

export const SE_JUNO: number;

export const SE_JUPITER: number;

export const SE_KRONOS: number;

export const SE_MARS: number;

export const SE_MAX_STNAME: number;

export const SE_MC: number;

export const SE_MEAN_APOG: number;

export const SE_MEAN_NODE: number;

export const SE_MERCURY: number;

export const SE_MIXEDOPIC_FLAG: number;

export const SE_MOON: number;

export const SE_MORNING_FIRST: number;

export const SE_MORNING_LAST: number;

export const SE_NALL_NAT_POINTS: number;

export const SE_NASCMC: number;

export const SE_NEPTUNE: number;

export const SE_NEPTUNE_ADAMS: number;

export const SE_NEPTUNE_LEVERRIER: number;

export const SE_NFICT_ELEM: number;

export const SE_NIBIRU: number;

export const SE_NODBIT_FOPOINT: number;

export const SE_NODBIT_MEAN: number;

export const SE_NODBIT_OSCU: number;

export const SE_NODBIT_OSCU_BAR: number;

export const SE_NPLANETS: number;

export const SE_NSIDM_PREDEF: number;

export const SE_OSCU_APOG: number;

export const SE_PALLAS: number;

export const SE_PHOLUS: number;

export const SE_PHOTOPIC_FLAG: number;

export const SE_PLUTO: number;

export const SE_PLUTO_LOWELL: number;

export const SE_PLUTO_PICKERING: number;

export const SE_POLASC: number;

export const SE_POSEIDON: number;

export const SE_PROSERPINA: number;

export const SE_SATURN: number;

export const SE_SCOTOPIC_FLAG: number;

export const SE_SIDBITS: number;

export const SE_SIDBIT_ECL_T0: number;

export const SE_SIDBIT_SSY_PLANE: number;

export const SE_SIDBIT_USER_UT: number;

export const SE_SIDM_ALDEBARAN_15TAU: number;

export const SE_SIDM_ARYABHATA: number;

export const SE_SIDM_ARYABHATA_522: number;

export const SE_SIDM_ARYABHATA_MSUN: number;

export const SE_SIDM_B1950: number;

export const SE_SIDM_BABYL_BRITTON: number;

export const SE_SIDM_BABYL_ETPSC: number;

export const SE_SIDM_BABYL_HUBER: number;

export const SE_SIDM_BABYL_KUGLER1: number;

export const SE_SIDM_BABYL_KUGLER2: number;

export const SE_SIDM_BABYL_KUGLER3: number;

export const SE_SIDM_DELUCE: number;

export const SE_SIDM_DJWHAL_KHUL: number;

export const SE_SIDM_FAGAN_BRADLEY: number;

export const SE_SIDM_GALALIGN_MARDYKS: number;

export const SE_SIDM_GALCENT_0SAG: number;

export const SE_SIDM_GALCENT_COCHRANE: number;

export const SE_SIDM_GALCENT_MULA_WILHELM: number;

export const SE_SIDM_GALCENT_RGILBRAND: number;

export const SE_SIDM_GALEQU_FIORENZA: number;

export const SE_SIDM_GALEQU_IAU1958: number;

export const SE_SIDM_GALEQU_MULA: number;

export const SE_SIDM_GALEQU_TRUE: number;

export const SE_SIDM_HIPPARCHOS: number;

export const SE_SIDM_J1900: number;

export const SE_SIDM_J2000: number;

export const SE_SIDM_JN_BHASIN: number;

export const SE_SIDM_KRISHNAMURTI: number;

export const SE_SIDM_LAHIRI: number;

export const SE_SIDM_RAMAN: number;

export const SE_SIDM_SASSANIAN: number;

export const SE_SIDM_SS_CITRA: number;

export const SE_SIDM_SS_REVATI: number;

export const SE_SIDM_SURYASIDDHANTA: number;

export const SE_SIDM_SURYASIDDHANTA_MSUN: number;

export const SE_SIDM_TRUE_CITRA: number;

export const SE_SIDM_TRUE_MULA: number;

export const SE_SIDM_TRUE_PUSHYA: number;

export const SE_SIDM_TRUE_REVATI: number;

export const SE_SIDM_TRUE_SHEORAN: number;

export const SE_SIDM_USER: number;

export const SE_SIDM_USHASHASHI: number;

export const SE_SIDM_VALENS_MOON: number;

export const SE_SIDM_YUKTESHWAR: number;

export const SE_SPLIT_DEG_KEEP_DEG: number;

export const SE_SPLIT_DEG_KEEP_SIGN: number;

export const SE_SPLIT_DEG_NAKSHATRA: number;

export const SE_SPLIT_DEG_ROUND_DEG: number;

export const SE_SPLIT_DEG_ROUND_MIN: number;

export const SE_SPLIT_DEG_ROUND_SEC: number;

export const SE_SPLIT_DEG_ZODIACAL: number;

export const SE_SUN: number;

export const SE_TRUE_NODE: number;

export const SE_TRUE_TO_APP: number;

export const SE_URANUS: number;

export const SE_VARUNA: number;

export const SE_VENUS: number;

export const SE_VERTEX: number;

export const SE_VESTA: number;

export const SE_VULCAN: number;

export const SE_VULKANUS: number;

export const SE_WALDEMATH: number;

export const SE_WHITE_MOON: number;

export const SE_ZEUS: number;

export const SIMULATE_VICTORVB: number;

export const TJD_INVALID: number;

export const ephemeris: {
    de200: string;
    de405: string;
    de406: string;
    de406e: string;
    de414: string;
    de421: string;
    de422: string;
    de430: string;
    de431: string;
    moshier: number;
    swisseph: number;
};

export function calc(options: any, callback: any): any;

export function swe_azalt(): any;

export function swe_azalt_rev(): any;

export function swe_calc(): any;

export function swe_calc_ut(): any;

export function swe_close(): any;

export function swe_cotrans(): any;

export function swe_cotrans_sp(): any;

export function swe_cs2degstr(): any;

export function swe_cs2lonlatstr(): any;

export function swe_cs2timestr(): any;

export function swe_csnorm(): any;

export function swe_csroundsec(): any;

export function swe_d2l(): any;

export function swe_date_conversion(): any;

export function swe_day_of_week(): any;

export function swe_deg_midp(): any;

export function swe_degnorm(): any;

export function swe_deltat(): any;

export function swe_difcs2n(): any;

export function swe_difcsn(): any;

export function swe_difdeg2n(): any;

export function swe_difdegn(): any;

export function swe_difrad2n(): any;

export function swe_fixstar(): any;

export function swe_fixstar2(): any;

export function swe_fixstar2_mag(): any;

export function swe_fixstar2_ut(): any;

export function swe_fixstar_mag(): any;

export function swe_fixstar_ut(): any;

export function swe_gauquelin_sector(): any;

export function swe_get_ayanamsa(): any;

export function swe_get_ayanamsa_ex(): any;

export function swe_get_ayanamsa_ex_ut(): any;

export function swe_get_ayanamsa_name(): any;

export function swe_get_ayanamsa_ut(): any;

export function swe_get_orbital_elements(): any;

export function swe_get_planet_name(): any;

export function swe_get_tid_acc(): any;

export function swe_heliacal_pheno_ut(): any;

export function swe_heliacal_ut(): any;

export function swe_houses(): any;

export function swe_houses_armc(): any;

export function swe_houses_ex(): any;

export function swe_houses_pos(): any;

export function swe_jdet_to_utc(): any;

export function swe_jdut1_to_utc(): any;

export function swe_julday(): any;

export function swe_lun_eclipse_how(): any;

export function swe_lun_eclipse_when(): any;

export function swe_lun_eclipse_when_loc(): any;

export function swe_lun_occult_when_glob(): any;

export function swe_lun_occult_when_loc(): any;

export function swe_lun_occult_where(): any;

export function swe_nod_aps(): any;

export function swe_nod_aps_ut(): any;

export function swe_orbit_max_min_true_distance(): any;

export function swe_pheno(): any;

export function swe_pheno_ut(): any;

export function swe_rad_midp(): any;

export function swe_radnorm(): any;

export function swe_refrac(): any;

export function swe_refrac_extended(): any;

export function swe_revjul(): any;

export function swe_rise_trans(): any;

export function swe_rise_trans_true_hor(): any;

export function swe_set_ephe_path(): any;

export function swe_set_jpl_file(): any;

export function swe_set_lapse_rate(): any;

export function swe_set_sid_mode(): any;

export function swe_set_tid_acc(): any;

export function swe_set_topo(): any;

export function swe_sidtime(): any;

export function swe_sidtime0(): any;

export function swe_sol_eclipse_how(): any;

export function swe_sol_eclipse_when_glob(): any;

export function swe_sol_eclipse_when_loc(): any;

export function swe_sol_eclipse_where(): any;

export function swe_split_deg(): any;

export function swe_time_equ(): any;

export function swe_utc_time_zone(): any;

export function swe_utc_to_jd(): any;

export function swe_version(): any;

export function swe_vis_limit_mag(): any;

