/** Declaration file generated by dts-gen */

export const SEFLG_ASTROMETRIC: number;

export const SEFLG_BARYCTR: number;

export const SEFLG_DEFAULTEPH: number;

export const SEFLG_DPSIDEPS_1980: number;

export const SEFLG_EQUATORIAL: number;

export const SEFLG_HELCTR: number;

export const SEFLG_ICRS: number;

export const SEFLG_J2000: number;

export const SEFLG_JPLEPH: number;

export const SEFLG_JPLHOR: number;

export const SEFLG_JPLHOR_APPROX: number;

export const SEFLG_MOSEPH: number;

export const SEFLG_NOABERR: number;

export const SEFLG_NOGDEFL: number;

export const SEFLG_NONUT: number;

export const SEFLG_ORBEL_AA: number;

export const SEFLG_RADIANS: number;

export const SEFLG_SIDEREAL: number;

export const SEFLG_SPEED: number;

export const SEFLG_SPEED3: number;

export const SEFLG_SWIEPH: number;

export const SEFLG_TOPOCTR: number;

export const SEFLG_TRUEPOS: number;

export const SEFLG_XYZ: number;

export const SE_ACRONYCHAL_RISING: number;

export const SE_ACRONYCHAL_SETTING: number;

export const SE_ADMETOS: number;

export const SE_APOLLON: number;

export const SE_APP_TO_TRUE: number;

export const SE_ARMC: number;

export const SE_ASC: number;

export const SE_AST_OFFSET: number;

export const SE_AUNIT_TO_KM: number;

export const SE_AUNIT_TO_LIGHTYEAR: number;

export const SE_AUNIT_TO_PARSEC: number;

export const SE_BIT_ASTRO_TWILIGHT: number;

export const SE_BIT_CIVIL_TWILIGHT: number;

export const SE_BIT_DISC_BOTTOM: number;

export const SE_BIT_DISC_CENTER: number;

export const SE_BIT_FIXED_DISC_SIZE: number;

export const SE_BIT_GEOCTR_NO_ECL_LAT: number;

export const SE_BIT_NAUTIC_TWILIGHT: number;

export const SE_BIT_NO_REFRACTION: number;

export const SE_CALC_ITRANSIT: number;

export const SE_CALC_MTRANSIT: number;

export const SE_CALC_RISE: number;

export const SE_CALC_SET: number;

export const SE_CERES: number;

export const SE_CHIRON: number;

export const SE_COASC1: number;

export const SE_COASC2: number;

export const SE_COMET_OFFSET: number;

export const SE_COSMICAL_SETTING: number;

export const SE_CUPIDO: number;

export const SE_EARTH: number;

export const SE_ECL2HOR: number;

export const SE_ECL_1ST_VISIBLE: number;

export const SE_ECL_2ND_VISIBLE: number;

export const SE_ECL_3RD_VISIBLE: number;

export const SE_ECL_4TH_VISIBLE: number;

export const SE_ECL_ALLTYPES_LUNAR: number;

export const SE_ECL_ALLTYPES_SOLAR: number;

export const SE_ECL_ANNULAR: number;

export const SE_ECL_ANNULAR_TOTAL: number;

export const SE_ECL_CENTRAL: number;

export const SE_ECL_MAX_VISIBLE: number;

export const SE_ECL_NONCENTRAL: number;

export const SE_ECL_NUT: number;

export const SE_ECL_OCC_BEG_DAYLIGHT: number;

export const SE_ECL_OCC_END_DAYLIGHT: number;

export const SE_ECL_ONE_TRY: number;

export const SE_ECL_PARTBEG_VISIBLE: number;

export const SE_ECL_PARTEND_VISIBLE: number;

export const SE_ECL_PARTIAL: number;

export const SE_ECL_PENUMBBEG_VISIBLE: number;

export const SE_ECL_PENUMBEND_VISIBLE: number;

export const SE_ECL_PENUMBRAL: number;

export const SE_ECL_TOTAL: number;

export const SE_ECL_TOTBEG_VISIBLE: number;

export const SE_ECL_TOTEND_VISIBLE: number;

export const SE_ECL_VISIBLE: number;

export const SE_EQU2HOR: number;

export const SE_EQUASC: number;

export const SE_EVENING_FIRST: number;

export const SE_EVENING_LAST: number;

export const SE_FICT_MAX: number;

export const SE_FICT_OFFSET: number;

export const SE_FICT_OFFSET_1: number;

export const SE_FIXSTAR: number;

export const SE_GREG_CAL: number;

export const SE_HADES: number;

export const SE_HARRINGTON: number;

export const SE_HELFLAG_AVKIND: number;

export const SE_HELFLAG_AVKIND_MIN7: number;

export const SE_HELFLAG_AVKIND_MIN9: number;

export const SE_HELFLAG_AVKIND_PTO: number;

export const SE_HELFLAG_AVKIND_VR: number;

export const SE_HELFLAG_HIGH_PRECISION: number;

export const SE_HELFLAG_LONG_SEARCH: number;

export const SE_HELFLAG_NO_DETAILS: number;

export const SE_HELFLAG_OPTICAL_PARAMS: number;

export const SE_HELFLAG_SEARCH_1_PERIOD: number;

export const SE_HELFLAG_VISLIM_DARK: number;

export const SE_HELFLAG_VISLIM_NOMOON: number;

export const SE_HELFLAG_VISLIM_PHOTOPIC: number;

export const SE_HELIACAL_RISING: number;

export const SE_HELIACAL_SETTING: number;

export const SE_HOR2ECL: number;

export const SE_HOR2EQU: number;

export const SE_INTP_APOG: number;

export const SE_INTP_PERG: number;

export const SE_ISIS: number;

export const SE_JUL_CAL: number;

export const SE_JUNO: number;

export const SE_JUPITER: number;

export const SE_KRONOS: number;

export const SE_MARS: number;

export const SE_MAX_STNAME: number;

export const SE_MC: number;

export const SE_MEAN_APOG: number;

export const SE_MEAN_NODE: number;

export const SE_MERCURY: number;

export const SE_MIXEDOPIC_FLAG: number;

export const SE_MOON: number;

export const SE_MORNING_FIRST: number;

export const SE_MORNING_LAST: number;

export const SE_NALL_NAT_POINTS: number;

export const SE_NASCMC: number;

export const SE_NEPTUNE: number;

export const SE_NEPTUNE_ADAMS: number;

export const SE_NEPTUNE_LEVERRIER: number;

export const SE_NFICT_ELEM: number;

export const SE_NIBIRU: number;

export const SE_NODBIT_FOPOINT: number;

export const SE_NODBIT_MEAN: number;

export const SE_NODBIT_OSCU: number;

export const SE_NODBIT_OSCU_BAR: number;

export const SE_NPLANETS: number;

export const SE_NSIDM_PREDEF: number;

export const SE_OSCU_APOG: number;

export const SE_PALLAS: number;

export const SE_PHOLUS: number;

export const SE_PHOTOPIC_FLAG: number;

export const SE_PLUTO: number;

export const SE_PLUTO_LOWELL: number;

export const SE_PLUTO_PICKERING: number;

export const SE_POLASC: number;

export const SE_POSEIDON: number;

export const SE_PROSERPINA: number;

export const SE_SATURN: number;

export const SE_SCOTOPIC_FLAG: number;

export const SE_SIDBITS: number;

export const SE_SIDBIT_ECL_T0: number;

export const SE_SIDBIT_SSY_PLANE: number;

export const SE_SIDBIT_USER_UT: number;

export const SE_SIDM_ALDEBARAN_15TAU: number;

export const SE_SIDM_ARYABHATA: number;

export const SE_SIDM_ARYABHATA_522: number;

export const SE_SIDM_ARYABHATA_MSUN: number;

export const SE_SIDM_B1950: number;

export const SE_SIDM_BABYL_BRITTON: number;

export const SE_SIDM_BABYL_ETPSC: number;

export const SE_SIDM_BABYL_HUBER: number;

export const SE_SIDM_BABYL_KUGLER1: number;

export const SE_SIDM_BABYL_KUGLER2: number;

export const SE_SIDM_BABYL_KUGLER3: number;

export const SE_SIDM_DELUCE: number;

export const SE_SIDM_DJWHAL_KHUL: number;

export const SE_SIDM_FAGAN_BRADLEY: number;

export const SE_SIDM_GALALIGN_MARDYKS: number;

export const SE_SIDM_GALCENT_0SAG: number;

export const SE_SIDM_GALCENT_COCHRANE: number;

export const SE_SIDM_GALCENT_MULA_WILHELM: number;

export const SE_SIDM_GALCENT_RGILBRAND: number;

export const SE_SIDM_GALEQU_FIORENZA: number;

export const SE_SIDM_GALEQU_IAU1958: number;

export const SE_SIDM_GALEQU_MULA: number;

export const SE_SIDM_GALEQU_TRUE: number;

export const SE_SIDM_HIPPARCHOS: number;

export const SE_SIDM_J1900: number;

export const SE_SIDM_J2000: number;

export const SE_SIDM_JN_BHASIN: number;

export const SE_SIDM_KRISHNAMURTI: number;

export const SE_SIDM_LAHIRI: number;

export const SE_SIDM_RAMAN: number;

export const SE_SIDM_SASSANIAN: number;

export const SE_SIDM_SS_CITRA: number;

export const SE_SIDM_SS_REVATI: number;

export const SE_SIDM_SURYASIDDHANTA: number;

export const SE_SIDM_SURYASIDDHANTA_MSUN: number;

export const SE_SIDM_TRUE_CITRA: number;

export const SE_SIDM_TRUE_MULA: number;

export const SE_SIDM_TRUE_PUSHYA: number;

export const SE_SIDM_TRUE_REVATI: number;

export const SE_SIDM_TRUE_SHEORAN: number;

export const SE_SIDM_USER: number;

export const SE_SIDM_USHASHASHI: number;

export const SE_SIDM_VALENS_MOON: number;

export const SE_SIDM_YUKTESHWAR: number;

export const SE_SPLIT_DEG_KEEP_DEG: number;

export const SE_SPLIT_DEG_KEEP_SIGN: number;

export const SE_SPLIT_DEG_NAKSHATRA: number;

export const SE_SPLIT_DEG_ROUND_DEG: number;

export const SE_SPLIT_DEG_ROUND_MIN: number;

export const SE_SPLIT_DEG_ROUND_SEC: number;

export const SE_SPLIT_DEG_ZODIACAL: number;

export const SE_SUN: number;

export const SE_TRUE_NODE: number;

export const SE_TRUE_TO_APP: number;

export const SE_URANUS: number;

export const SE_VARUNA: number;

export const SE_VENUS: number;

export const SE_VERTEX: number;

export const SE_VESTA: number;

export const SE_VULCAN: number;

export const SE_VULKANUS: number;

export const SE_WALDEMATH: number;

export const SE_WHITE_MOON: number;

export const SE_ZEUS: number;

export const SIMULATE_VICTORVB: number;

export const TJD_INVALID: number;

export const ephemeris: {
    de200: string;
    de405: string;
    de406: string;
    de406e: string;
    de414: string;
    de421: string;
    de422: string;
    de430: string;
    de431: string;
    moshier: number;
    swisseph: number;
};

export function calc(options: any, callback: any): any;

export function swe_calc_ut(tjd_ut: number, ipl: number, iflag: number, xx: number, serr: string): number;
export function swe_date_conversion(y: number, m: number, d: number,hour: number,c: string,tjd: number): number;
export function swe_azalt_rev(tjd_ut: number,calc_flag: number,geopos: number,xin: number,xout: number): void;
export function swe_azalt(tjd_ut: number,calc_flag: number,geopos: number,atpress: number,attemp: number,xin: number,xaz: number): void;
export function swe_calc(tjd_et: number, ipl: number, iflag: number, xx: number, serr: string): number;
export function swe_close(): void;
export function swe_cotrans_sp(xpo: number,xpn: number,eps: number): void;
export function swe_cotrans(xpo: number,xpn: number,eps: number): void;
export function swe_cs2degstr(t: number, a: string): string;
export function swe_cs2lonlatstr(t: number, pchar: string, mchar: string, s: string): string;
export function swe_cs2timestr(t: number, sep: number, suppressZero: boolean, a: string): string;
export function swe_csroundsec(x: number): number;
export function swe_d2l(x: number): number;
export function swe_day_of_week(jd: number): number;
export function swe_degnorm(x: number): number;
export function swe_deltat_ex(tjd: number,ephe_flag: number,serr: string): number;
export function swe_deltat(tjd: number): number;
export function swe_difcs2n(p1: number, p2: number): number;
export function swe_difcsn(p1: number, p2: number): number;
export function swe_difdeg2n(p1: number, p2: number): number;
export function swe_difdegn(p1: number, p2: number): number;
export function swe_fixstar_ut(star: string, tjd_ut: number, iflag: number, xx: number, serr: string): number;
export function swe_fixstar(star: string, tjd_et: number, iflag: number, xx: number, serr: string): number;
export function swe_gauquelin_sector(tjd_ut: number,ipl: number,starname: string,iflag: number,imeth: number,geopos: number,atpress: number, attemp: number,dgsect: number,serr: string): number;
export function swe_get_ayanamsa_ex_ut(tjd_ut: number, ephe_flag: number, daya: number, serr: string): number;
export function swe_get_ayanamsa_ex(tjd_ut: number, ephe_flag: number, daya: number, serr: string): number;
export function swe_get_ayanamsa_ut(tjd_ut: number): number;
export function swe_get_ayanamsa(tjd_et: number): number;
export function swe_get_library_path(spath: string): string;
export function swe_get_planet_name(ipl: number,plan_name: string): string;
export function swe_get_tid_acc(): number;
export function swe_house_name(hsys: number): string;
export function swe_house_pos(armc: number,geolat: number,eps: number,hsys: number,xpin: number,serr: string): number;
export function swe_houses_armc(armc: number,geolat: number,eps: number,hsys: number,cusps: number,ascmc: number): number;
export function swe_houses_ex(tjd_ut: number,iflag: number,geolat: number,geolon: number,hsys: number,cusps: number,ascmc: number): number;
export function swe_houses(tjd_ut: number,geolat: number,geolon: number,hsys: number,cusps: number,ascmc: number): number;
export function swe_jdet_to_utc(tjd_et: number,gregflag: number, iyear: number, imonth: number, iday: number,ihour: number, imin: number, dsec: number): void;
export function swe_jdut1_to_utc(tjd_ut: number,gregflag: number, iyear: number, imonth: number, iday: number,ihour: number, imin: number, dsec: number): void;
export function swe_julday(year: number,month: number,day: number,hour: number,gregflag: number) : number;
export function swe_lat_to_lmt(tjd_lat: number,geolon: number,tjd_lmt: number,serr: string): number;
export function swe_lmt_to_lat(tjd_lmt: number,geolon: number,tjd_lat: number,serr: string): number;
export function swe_lun_eclipse_how(tjd_ut: number,ifl: number,geopos: number, attr: number,serr: string): number;
export function swe_lun_eclipse_when_loc(tjd_start: number,ifl: number,geopos: number,tret: number,attr: number, backward: boolean,serr: string): number;
export function swe_lun_eclipse_when(tjd_start: number,ifl: number,ifltype: number,tret: number,backward: boolean,serr: string): number;
export function swe_lun_occult_when_glob(tjd_start: number, ipl: number, starname: string, ifl: number, ifltype: number, tret: number, backward: boolean, serr: string): number;
export function swe_lun_occult_when_loc(tjd_start: number, ipl: number, starname: string, ifl: number, geopos: number, tret: number, attr: number, backward: boolean, serr: string): number;
export function swe_lun_occult_where(tjd_ut: number, ipl: number, starname: string, ifl: number, geopos: number, attr: number, serr: string): number;
export function swe_pheno_ut(tjd_ut: number,ipl: number,iflag: number,attr: number,serr: string): number;
export function swe_pheno(tjd_et: number,ipl: number,iflag: number,attr: number,serr: string): number;
export function swe_radnorm(x: number): number;
export function swe_refrac(inalt: number,atpress: number,attemp: number, calc_flag: number): number;
export function swe_revjul(tjd: number,gregflag: number,year: number,month: number,day: number,hour: number): void;
export function swe_rise_trans_true_hor(tjd_ut: number,ipl: number,starname: string,epheflag: number,rsmi: number,geopos: number,atpress: number,attemp: number,horhgt: number,tret: number,serr: string): number;
export function swe_rise_trans(tjd_ut: number,ipl: number,starname: string,epheflag: number,rsmi: number,geopos: number,atpress: number,attemp: number,tret: number,serr: string): number;
export function swe_set_ephe_path(path: string): void;
export function swe_set_jpl_file(fname: string): void;
export function swe_set_sid_mode(sid_mode: number,t0: number, ayan_t0: number): void;
export function swe_set_tid_acc(t_acc: number): void;
export function swe_set_topo(geolon: number, geolat: number, altitude: number): void;
export function swe_sidtime(tjd_ut: number): number;
export function swe_sidtime0(tjd_ut: number,eps: number,nut: number): number;
export function swe_sol_eclipse_how(tjd_ut: number, ifl: number, geopos: number, attr: number, serr: string): number;
export function swe_sol_eclipse_when_glob(tjd_start: number, ifl: number, ifltype: number, tret: number, backward: boolean, serr: string): number;
export function swe_sol_eclipse_when_loc(tjd_start: number, ifl: number, geopos: number, tret: number, attr: number, backward: boolean, serr: string): number;
export function swe_sol_eclipse_where(tjd_ut: number, ifl: number, geopos: number, attr: number, serr: string): number;
export function swe_split_deg(ddeg: number,roundflag: number,ideg: number,imin: number,isec: number,dsecfr: number,isgn: number): number;
export function swe_time_equ(tjd_et: number,e: number,serr: string): number;
export function swe_utc_timezone(iyear: number, imonth: number, iday: number,ihour: number, imin: number, dsec: number,d_timezone: number,iyear_out: number, imonth_out: number, iday_out: number,ihour_out: number, imin_out: number, dsec_out: number): void;
export function swe_utc_to_jd(iyear: number, imonth: number, iday: number,ihour: number, imin: number, dsec: number,gregflag: number, dret: number[], serr: string): void;
export function swe_version(svers: string): string;
